export const TABLE_TURMA = "labenu_system_turma"
export const TABLE_ESTUDANTE = "labenu_system_estudante"
export const TABLE_ESTUDANTE_HOBBY = "labenu_system_estudante_hobby"
export const TABLE_HOBBY = "labenu_system_hobby"
export const TABLE_DOCENTE = "labenu_system_docente"
export const TABLE_DOCENTE_ESPECIALIDADE = "labenu_system_docente_especialidade"
export const TABLE_ESPECIALIDADE = "labenu_system_especialidade"